# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81813b99b09e8af2660da0c372a5588a5d3712f7917d1506a3fffcd8e0ada65a49ac6ea2a6f16ed26378f3368db53c8578039c802445fe1e71408635a65a6225

test:
  secret_key_base: 9818ac799e2d67d7d210ca70d3907595c8cd41b7dabc49d070edce6500188f5997a3d12f372d6c9ba0d66df73ee1be44042bc8459a8f55ebc44773abc3b28039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
